spring:
  profiles:
    active: local
  application:
    name: Shoply-Backend
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: INFO
    com.Shoply_Backend: INFO
    org.springframework: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}