spring:
  application:
    name: Shoply-Backend
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

config:
  import: optional:file:.env[.properties]

jwt:
  secret: hkJ5eZRGnTuXH01uIZ9lNVR/rzWDq6X5ZZofzlTuoR8ouQ6xKqKvK5KBYcMJzBsQ
  expiration: 86400000

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG