spring:
  application:
    name: Shoply-Backend
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

config:
  import: optional:file:.env[.properties]

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG